
version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017"

  app:
    build: .
    ports:
      - "3000:8080"
    depends_on:
      - mongo
volumes:
  data: {}



